# Generated by Django 2.2.1 on 2019-05-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('desc', models.CharField(max_length=255, verbose_name='噱头描述')),
                ('occupation', models.CharField(max_length=50, verbose_name='职业')),
            ],
            options={
                'verbose_name': '评审团',
                'verbose_name_plural': '评审团',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=255, verbose_name='大致描述')),
                ('content', models.CharField(max_length=8000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('ID_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='公司名称')),
                ('score', models.IntegerField(max_length=3, verbose_name='群众打分')),
                ('complaint_amount', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='投诉数量')),
                ('is_red', models.BooleanField(default=False, verbose_name='是否在红榜')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category')),
            ],
            options={
                'verbose_name': '红黑榜',
                'verbose_name_plural': '红黑榜',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=255, verbose_name='大致描述')),
                ('content', models.CharField(max_length=8000, verbose_name='内容')),
                ('page_view_amount', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='浏览量')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.User')),
            ],
            options={
                'verbose_name': '投诉表',
                'verbose_name_plural': '投诉表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=8000, verbose_name='内容')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Complaint')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.User')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
    ]
