# Generated by Django 2.2.1 on 2019-05-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190516_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='jury',
            name='update_time',
        ),
        migrations.AddField(
            model_name='company',
            name='company_introduce',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司简介'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='collection_complaint',
            name='collected_complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='collection_complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='collection_user',
            name='collected_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collected_uid', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='collection_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uid', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_head',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司标志'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='hot_complaint',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='hot_news',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.news'),
        ),
        migrations.AlterField(
            model_name='jury',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='latest_complaint',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
    ]
