# Generated by Django 2.2.1 on 2019-05-31 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190531_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_complaint',
            name='collected_complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='collection_complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='collection_user',
            name='collected_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collected_uid', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='collection_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uid', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='hot_complaint',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.AlterField(
            model_name='hot_news',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.news'),
        ),
        migrations.AlterField(
            model_name='latest_complaint',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.complaint'),
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
    ]
